### ISSUE TITLE
Modified files should always have the indicator visible

### ISSUE THREAD

**Issue by doman412** [Yummygum/city-lights-ui-atom#20]
Currently, the 'file is modified' indicator is only visible if that tab is active. I've added this to my stylesheets to fix it, but should be native, or at lease an option.

```less
.tab-bar .tab.modified:not(:hover) .close-icon {
  // keep the modified indicator live regardless of active-ness
  opacity: 1;
}
```
