### ISSUE TITLE
scroll bar always shows for project folder on mac

### ISSUE THREAD

**Issue by jason919** [Yummygum/city-lights-ui-atom#29]
scroll bar always shows for project folder on mac, can it hide itself.

**Comment by noudadrichem** [comment]
Hi @jason919,

Can you explain your specific issue a little bit more in dept?

**Comment by arich55** [comment]
When viewing projects in the tree view or application files, the default theme hides the scroll bars on hover off and shows them again when the mouse cursor is hovered on it. In this theme however, the scrollbars are always permanently visible. Is there a way to have them removed when not in focus?

![screen shot 2018-02-15 at 10 36 58 pm](https://user-images.githubusercontent.com/1228252/36292627-1280472e-12a1-11e8-9ac2-25a045b09ba4.png)

**Comment by arich55** [comment]
Added the following to styles.less to resolve.

```css
// hide scrollbars
&::-webkit-scrollbar{
  display: none;
  width: 0.35rem;
  height: 0.35rem;
}
&:hover::-webkit-scrollbar{
  display: block;
}
```
