### ISSUE TITLE
Scrollbar match theme

### ISSUE THREAD

**Issue by tbremer** [Yummygum/city-lights-ui-atom#7]
Hey all! This is a great theme, in combination with the Syntax and Icons it's _really_ well thought out. Very nice!

I found it odd that the scrollbars weren't styled. Would you be open to a pull request? I came up with this as a solution (locally):

```less
@import "ui-variables";

::-webkit-scrollbar-corner {
  background-color: transparent;
}

::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-thumb {
  border-radius: 2px;
  background: @text-color-highlight;
}
```

Screenshot:
![screen shot 2017-11-07 at 11 42 24 am](https://user-images.githubusercontent.com/2998575/32508723-d8a0ef52-c3b0-11e7-8dc1-66e737ec18b7.png)
